export const Footer = () => import('../../components/footer.vue' /* webpackChunkName: "components/footer" */).then(c => wrapFunctional(c.default || c))
export const GnbHeader = () => import('../../components/gnbHeader.vue' /* webpackChunkName: "components/gnb-header" */).then(c => wrapFunctional(c.default || c))
export const Header = () => import('../../components/header.vue' /* webpackChunkName: "components/header" */).then(c => wrapFunctional(c.default || c))
export const ApiAxios = () => import('../../components/api/axios.js' /* webpackChunkName: "components/api-axios" */).then(c => wrapFunctional(c.default || c))
export const DummyAward = () => import('../../components/dummy/award.js' /* webpackChunkName: "components/dummy-award" */).then(c => wrapFunctional(c.default || c))
export const DummyAwardEn = () => import('../../components/dummy/awardEn.js' /* webpackChunkName: "components/dummy-award-en" */).then(c => wrapFunctional(c.default || c))
export const MainBannerModule = () => import('../../components/main/bannerModule.vue' /* webpackChunkName: "components/main-banner-module" */).then(c => wrapFunctional(c.default || c))
export const MainCompany = () => import('../../components/main/company.vue' /* webpackChunkName: "components/main-company" */).then(c => wrapFunctional(c.default || c))
export const MainCompanyAwards = () => import('../../components/main/companyAwards.vue' /* webpackChunkName: "components/main-company-awards" */).then(c => wrapFunctional(c.default || c))
export const MainCtaModule = () => import('../../components/main/ctaModule.vue' /* webpackChunkName: "components/main-cta-module" */).then(c => wrapFunctional(c.default || c))
export const MainBanner = () => import('../../components/main/mainBanner.vue' /* webpackChunkName: "components/main-banner" */).then(c => wrapFunctional(c.default || c))
export const MainSlider = () => import('../../components/main/mainSlider.vue' /* webpackChunkName: "components/main-slider" */).then(c => wrapFunctional(c.default || c))
export const MainProducts = () => import('../../components/main/products.vue' /* webpackChunkName: "components/main-products" */).then(c => wrapFunctional(c.default || c))
export const MainSlideCarousel = () => import('../../components/main/slideCarousel.vue' /* webpackChunkName: "components/main-slide-carousel" */).then(c => wrapFunctional(c.default || c))
export const MainSuppoert = () => import('../../components/main/suppoert.vue' /* webpackChunkName: "components/main-suppoert" */).then(c => wrapFunctional(c.default || c))
export const MainUseCase = () => import('../../components/main/useCase.vue' /* webpackChunkName: "components/main-use-case" */).then(c => wrapFunctional(c.default || c))
export const MixinsMixin = () => import('../../components/mixins/mixin.js' /* webpackChunkName: "components/mixins-mixin" */).then(c => wrapFunctional(c.default || c))
export const ModulesBanner = () => import('../../components/modules/Banner.vue' /* webpackChunkName: "components/modules-banner" */).then(c => wrapFunctional(c.default || c))
export const ModulesBoard = () => import('../../components/modules/Board.vue' /* webpackChunkName: "components/modules-board" */).then(c => wrapFunctional(c.default || c))
export const ModulesBoardView = () => import('../../components/modules/BoardView.vue' /* webpackChunkName: "components/modules-board-view" */).then(c => wrapFunctional(c.default || c))
export const ModulesCalculatorPopup = () => import('../../components/modules/CalculatorPopup.vue' /* webpackChunkName: "components/modules-calculator-popup" */).then(c => wrapFunctional(c.default || c))
export const ModulesDialogMobile = () => import('../../components/modules/Dialog-Mobile.vue' /* webpackChunkName: "components/modules-dialog-mobile" */).then(c => wrapFunctional(c.default || c))
export const ModulesDropdown = () => import('../../components/modules/Dropdown.vue' /* webpackChunkName: "components/modules-dropdown" */).then(c => wrapFunctional(c.default || c))
export const ModulesGallery = () => import('../../components/modules/Gallery.vue' /* webpackChunkName: "components/modules-gallery" */).then(c => wrapFunctional(c.default || c))
export const ModulesHeading = () => import('../../components/modules/Heading.vue' /* webpackChunkName: "components/modules-heading" */).then(c => wrapFunctional(c.default || c))
export const ModulesLibrary = () => import('../../components/modules/Library.vue' /* webpackChunkName: "components/modules-library" */).then(c => wrapFunctional(c.default || c))
export const ModulesLibraryView = () => import('../../components/modules/LibraryView.vue' /* webpackChunkName: "components/modules-library-view" */).then(c => wrapFunctional(c.default || c))
export const ModulesNewsletter = () => import('../../components/modules/Newsletter.vue' /* webpackChunkName: "components/modules-newsletter" */).then(c => wrapFunctional(c.default || c))
export const ModulesPopup = () => import('../../components/modules/Popup.vue' /* webpackChunkName: "components/modules-popup" */).then(c => wrapFunctional(c.default || c))
export const ModulesPopupConfirm = () => import('../../components/modules/PopupConfirm.vue' /* webpackChunkName: "components/modules-popup-confirm" */).then(c => wrapFunctional(c.default || c))
export const ModulesPopupVideo = () => import('../../components/modules/PopupVideo.vue' /* webpackChunkName: "components/modules-popup-video" */).then(c => wrapFunctional(c.default || c))
export const ModulesRequiredPopup = () => import('../../components/modules/RequiredPopup.vue' /* webpackChunkName: "components/modules-required-popup" */).then(c => wrapFunctional(c.default || c))
export const ModulesSnb = () => import('../../components/modules/Snb.vue' /* webpackChunkName: "components/modules-snb" */).then(c => wrapFunctional(c.default || c))
export const ModulesSubSolutionMenu = () => import('../../components/modules/SubSolutionMenu.vue' /* webpackChunkName: "components/modules-sub-solution-menu" */).then(c => wrapFunctional(c.default || c))
export const ModulesSupportModule = () => import('../../components/modules/SupportModule.vue' /* webpackChunkName: "components/modules-support-module" */).then(c => wrapFunctional(c.default || c))
export const ModulesYoutubeFullscreen = () => import('../../components/modules/YoutubeFullscreen.vue' /* webpackChunkName: "components/modules-youtube-fullscreen" */).then(c => wrapFunctional(c.default || c))
export const NewsCommonBaner = () => import('../../components/news/CommonBaner.vue' /* webpackChunkName: "components/news-common-baner" */).then(c => wrapFunctional(c.default || c))
export const Paging = () => import('../../components/paging/paging.vue' /* webpackChunkName: "components/paging" */).then(c => wrapFunctional(c.default || c))
export const PolicySubMenuPayment = () => import('../../components/policy/subMenuPayment.vue' /* webpackChunkName: "components/policy-sub-menu-payment" */).then(c => wrapFunctional(c.default || c))
export const PolicySubMenuPolicy = () => import('../../components/policy/subMenuPolicy.vue' /* webpackChunkName: "components/policy-sub-menu-policy" */).then(c => wrapFunctional(c.default || c))
export const PolicySubMenuTerms = () => import('../../components/policy/subMenuTerms.vue' /* webpackChunkName: "components/policy-sub-menu-terms" */).then(c => wrapFunctional(c.default || c))
export const ProductsNewBgPartData = () => import('../../components/products/NewBgPartData.js' /* webpackChunkName: "components/products-new-bg-part-data" */).then(c => wrapFunctional(c.default || c))
export const ProductsNewEffectPartData = () => import('../../components/products/newEffectPartData.js' /* webpackChunkName: "components/products-new-effect-part-data" */).then(c => wrapFunctional(c.default || c))
export const ProductsNewEffectPartDataEn = () => import('../../components/products/newEffectPartData_en.js' /* webpackChunkName: "components/products-new-effect-part-data-en" */).then(c => wrapFunctional(c.default || c))
export const ProductsNewModuleData = () => import('../../components/products/newModuleData.js' /* webpackChunkName: "components/products-new-module-data" */).then(c => wrapFunctional(c.default || c))
export const SubscriptionComForm = () => import('../../components/subscription/comForm.vue' /* webpackChunkName: "components/subscription-com-form" */).then(c => wrapFunctional(c.default || c))
export const SubscriptionComModal = () => import('../../components/subscription/comModal.vue' /* webpackChunkName: "components/subscription-com-modal" */).then(c => wrapFunctional(c.default || c))
export const SubscriptionForm = () => import('../../components/subscription/form.vue' /* webpackChunkName: "components/subscription-form" */).then(c => wrapFunctional(c.default || c))
export const SubscriptionModal = () => import('../../components/subscription/modal.vue' /* webpackChunkName: "components/subscription-modal" */).then(c => wrapFunctional(c.default || c))
export const SubscriptionProForm = () => import('../../components/subscription/proForm.vue' /* webpackChunkName: "components/subscription-pro-form" */).then(c => wrapFunctional(c.default || c))
export const SubscriptionProModal = () => import('../../components/subscription/proModal.vue' /* webpackChunkName: "components/subscription-pro-modal" */).then(c => wrapFunctional(c.default || c))
export const SupportSubMenu = () => import('../../components/support/SubMenu.vue' /* webpackChunkName: "components/support-sub-menu" */).then(c => wrapFunctional(c.default || c))
export const SupportFaq = () => import('../../components/support/faq.vue' /* webpackChunkName: "components/support-faq" */).then(c => wrapFunctional(c.default || c))
export const SupportFaqBanner = () => import('../../components/support/faqBanner.vue' /* webpackChunkName: "components/support-faq-banner" */).then(c => wrapFunctional(c.default || c))
export const SupportHeadBanner = () => import('../../components/support/headBanner.vue' /* webpackChunkName: "components/support-head-banner" */).then(c => wrapFunctional(c.default || c))
export const SupportInquiry = () => import('../../components/support/inquiry.vue' /* webpackChunkName: "components/support-inquiry" */).then(c => wrapFunctional(c.default || c))
export const SupportInquiryBanner = () => import('../../components/support/inquiryBanner.vue' /* webpackChunkName: "components/support-inquiry-banner" */).then(c => wrapFunctional(c.default || c))
export const SupportLearnBanner = () => import('../../components/support/learnBanner.vue' /* webpackChunkName: "components/support-learn-banner" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenter = () => import('../../components/support/learning-center.vue' /* webpackChunkName: "components/support-learning-center" */).then(c => wrapFunctional(c.default || c))
export const SupportNotice = () => import('../../components/support/notice.vue' /* webpackChunkName: "components/support-notice" */).then(c => wrapFunctional(c.default || c))
export const GnbCompany = () => import('../../components/Gnb/Company/index.vue' /* webpackChunkName: "components/gnb-company" */).then(c => wrapFunctional(c.default || c))
export const GnbContact = () => import('../../components/Gnb/Contact/index.vue' /* webpackChunkName: "components/gnb-contact" */).then(c => wrapFunctional(c.default || c))
export const GnbFreeTrials = () => import('../../components/Gnb/FreeTrials/index.vue' /* webpackChunkName: "components/gnb-free-trials" */).then(c => wrapFunctional(c.default || c))
export const GnbPricing = () => import('../../components/Gnb/Pricing/index.vue' /* webpackChunkName: "components/gnb-pricing" */).then(c => wrapFunctional(c.default || c))
export const GnbProducts = () => import('../../components/Gnb/Products/index.vue' /* webpackChunkName: "components/gnb-products" */).then(c => wrapFunctional(c.default || c))
export const GnbSolution = () => import('../../components/Gnb/Solution/index.vue' /* webpackChunkName: "components/gnb-solution" */).then(c => wrapFunctional(c.default || c))
export const GnbHeaderPartialMobileHeader = () => import('../../components/Gnb/headerPartial/mobileHeader.vue' /* webpackChunkName: "components/gnb-header-partial-mobile-header" */).then(c => wrapFunctional(c.default || c))
export const CompanyPagesRecruit = () => import('../../components/company/pages/Recruit.vue' /* webpackChunkName: "components/company-pages-recruit" */).then(c => wrapFunctional(c.default || c))
export const CompanyPagesBrand = () => import('../../components/company/pages/brand.vue' /* webpackChunkName: "components/company-pages-brand" */).then(c => wrapFunctional(c.default || c))
export const CompanyValue = () => import('../../components/company/pages/companyValue.vue' /* webpackChunkName: "components/company-value" */).then(c => wrapFunctional(c.default || c))
export const CompanyPagesIntroduce = () => import('../../components/company/pages/introduce.vue' /* webpackChunkName: "components/company-pages-introduce" */).then(c => wrapFunctional(c.default || c))
export const CompanyPartialsContactModule = () => import('../../components/company/partials/contactModule.vue' /* webpackChunkName: "components/company-partials-contact-module" */).then(c => wrapFunctional(c.default || c))
export const CompanyPartialsSubMenu = () => import('../../components/company/partials/subMenu.vue' /* webpackChunkName: "components/company-partials-sub-menu" */).then(c => wrapFunctional(c.default || c))
export const CompanyPartialsSubMenuBrand = () => import('../../components/company/partials/subMenuBrand.vue' /* webpackChunkName: "components/company-partials-sub-menu-brand" */).then(c => wrapFunctional(c.default || c))
export const CompanyPartialsSubMenuIr = () => import('../../components/company/partials/subMenuIr.vue' /* webpackChunkName: "components/company-partials-sub-menu-ir" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesMS = () => import('../../components/products/pages/MS.vue' /* webpackChunkName: "components/products-pages-m-s" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesMake = () => import('../../components/products/pages/Make.vue' /* webpackChunkName: "components/products-pages-make" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesPmain = () => import('../../components/products/pages/Pmain.vue' /* webpackChunkName: "components/products-pages-pmain" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesRemote = () => import('../../components/products/pages/Remote.vue' /* webpackChunkName: "components/products-pages-remote" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesTrack = () => import('../../components/products/pages/Track.vue' /* webpackChunkName: "components/products-pages-track" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesTwin = () => import('../../components/products/pages/Twin.vue' /* webpackChunkName: "components/products-pages-twin" */).then(c => wrapFunctional(c.default || c))
export const ProductsPagesView = () => import('../../components/products/pages/View.vue' /* webpackChunkName: "components/products-pages-view" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsBenefitPart = () => import('../../components/products/partials/BenefitPart.vue' /* webpackChunkName: "components/products-partials-benefit-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsBgSlidePart = () => import('../../components/products/partials/BgSlidePart.vue' /* webpackChunkName: "components/products-partials-bg-slide-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsEffectPart = () => import('../../components/products/partials/EffectPart.vue' /* webpackChunkName: "components/products-partials-effect-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsExamplePart = () => import('../../components/products/partials/ExamplePart.vue' /* webpackChunkName: "components/products-partials-example-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsFunctionPart = () => import('../../components/products/partials/FunctionPart.vue' /* webpackChunkName: "components/products-partials-function-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsFunctionPart2 = () => import('../../components/products/partials/FunctionPart2.vue' /* webpackChunkName: "components/products-partials-function-part2" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsIntroducePart = () => import('../../components/products/partials/IntroducePart.vue' /* webpackChunkName: "components/products-partials-introduce-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsNewBgSlide = () => import('../../components/products/partials/NewBgSlide.vue' /* webpackChunkName: "components/products-partials-new-bg-slide" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsNewEffectPart = () => import('../../components/products/partials/NewEffectPart.vue' /* webpackChunkName: "components/products-partials-new-effect-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsMainBanner = () => import('../../components/products/partials/ProductsMainBanner.vue' /* webpackChunkName: "components/products-main-banner" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSupportPart = () => import('../../components/products/partials/SupportPart.vue' /* webpackChunkName: "components/products-partials-support-part" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsXRSolution = () => import('../../components/products/partials/XRSolution.vue' /* webpackChunkName: "components/products-partials-x-r-solution" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsBottomBannerRemote = () => import('../../components/products/partials/bottomBannerRemote.vue' /* webpackChunkName: "components/products-partials-bottom-banner-remote" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsDataModule = () => import('../../components/products/partials/dataModule.vue' /* webpackChunkName: "components/products-partials-data-module" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsNavi = () => import('../../components/products/partials/navi.vue' /* webpackChunkName: "components/products-partials-navi" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsNewModule = () => import('../../components/products/partials/newModule.vue' /* webpackChunkName: "components/products-partials-new-module" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsProductProperty = () => import('../../components/products/partials/productProperty.vue' /* webpackChunkName: "components/products-partials-product-property" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubBanner = () => import('../../components/products/partials/subBanner.vue' /* webpackChunkName: "components/products-partials-sub-banner" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubBannerMake = () => import('../../components/products/partials/subBannerMake.vue' /* webpackChunkName: "components/products-partials-sub-banner-make" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubBannerTrack = () => import('../../components/products/partials/subBannerTrack.vue' /* webpackChunkName: "components/products-partials-sub-banner-track" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubBannerTwin = () => import('../../components/products/partials/subBannerTwin.vue' /* webpackChunkName: "components/products-partials-sub-banner-twin" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubBannerView = () => import('../../components/products/partials/subBannerView.vue' /* webpackChunkName: "components/products-partials-sub-banner-view" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubMenuMake = () => import('../../components/products/partials/subMenuMake.vue' /* webpackChunkName: "components/products-partials-sub-menu-make" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubMenuMs = () => import('../../components/products/partials/subMenuMs.vue' /* webpackChunkName: "components/products-partials-sub-menu-ms" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubMenuProduct = () => import('../../components/products/partials/subMenuProduct.vue' /* webpackChunkName: "components/products-partials-sub-menu-product" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubMenuTrack = () => import('../../components/products/partials/subMenuTrack.vue' /* webpackChunkName: "components/products-partials-sub-menu-track" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubMenuTwin = () => import('../../components/products/partials/subMenuTwin.vue' /* webpackChunkName: "components/products-partials-sub-menu-twin" */).then(c => wrapFunctional(c.default || c))
export const ProductsPartialsSubMenuView = () => import('../../components/products/partials/subMenuView.vue' /* webpackChunkName: "components/products-partials-sub-menu-view" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPagesAirline = () => import('../../components/solutions/pages/Airline.vue' /* webpackChunkName: "components/solutions-pages-airline" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPagesEPC = () => import('../../components/solutions/pages/EPC.vue' /* webpackChunkName: "components/solutions-pages-e-p-c" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPagesEnergy = () => import('../../components/solutions/pages/Energy.vue' /* webpackChunkName: "components/solutions-pages-energy" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPagesMotor = () => import('../../components/solutions/pages/Motor.vue' /* webpackChunkName: "components/solutions-pages-motor" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPagesOil = () => import('../../components/solutions/pages/Oil.vue' /* webpackChunkName: "components/solutions-pages-oil" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsBgNormalPart = () => import('../../components/solutions/partials/BgNormalPart.vue' /* webpackChunkName: "components/solutions-partials-bg-normal-part" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsInfographicPart = () => import('../../components/solutions/partials/InfographicPart.vue' /* webpackChunkName: "components/solutions-partials-infographic-part" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsIssuePart = () => import('../../components/solutions/partials/IssuePart.vue' /* webpackChunkName: "components/solutions-partials-issue-part" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsOfferPart = () => import('../../components/solutions/partials/OfferPart.vue' /* webpackChunkName: "components/solutions-partials-offer-part" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsRoiPart = () => import('../../components/solutions/partials/RoiPart.vue' /* webpackChunkName: "components/solutions-partials-roi-part" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsSubMenu = () => import('../../components/solutions/partials/subMenu.vue' /* webpackChunkName: "components/solutions-partials-sub-menu" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsSubMenuAirLine = () => import('../../components/solutions/partials/subMenuAirLine.vue' /* webpackChunkName: "components/solutions-partials-sub-menu-air-line" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsSubMenuEpc = () => import('../../components/solutions/partials/subMenuEpc.vue' /* webpackChunkName: "components/solutions-partials-sub-menu-epc" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsSubMenuMotor = () => import('../../components/solutions/partials/subMenuMotor.vue' /* webpackChunkName: "components/solutions-partials-sub-menu-motor" */).then(c => wrapFunctional(c.default || c))
export const SolutionsPartialsSubMenuOil = () => import('../../components/solutions/partials/subMenuOil.vue' /* webpackChunkName: "components/solutions-partials-sub-menu-oil" */).then(c => wrapFunctional(c.default || c))
export const SupportFaqAsideMenu = () => import('../../components/support/faq/AsideMenu.vue' /* webpackChunkName: "components/support-faq-aside-menu" */).then(c => wrapFunctional(c.default || c))
export const SupportFaqContents = () => import('../../components/support/faq/FaqContents.vue' /* webpackChunkName: "components/support-faq-contents" */).then(c => wrapFunctional(c.default || c))
export const SupportFaqGoogleMap = () => import('../../components/support/faq/GoogleMap.vue' /* webpackChunkName: "components/support-faq-google-map" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenterAsideMenu = () => import('../../components/support/learning-center/AsideMenu.vue' /* webpackChunkName: "components/support-learning-center-aside-menu" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenterListTabMenu = () => import('../../components/support/learning-center/ListTabMenu.vue' /* webpackChunkName: "components/support-learning-center-list-tab-menu" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenterStaticModule = () => import('../../components/support/learning-center/StaticModule.vue' /* webpackChunkName: "components/support-learning-center-static-module" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenterUserManual = () => import('../../components/support/learning-center/userManual.vue' /* webpackChunkName: "components/support-learning-center-user-manual" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenterVideoRealGuide = () => import('../../components/support/learning-center/videoRealGuide.vue' /* webpackChunkName: "components/support-learning-center-video-real-guide" */).then(c => wrapFunctional(c.default || c))
export const SupportLearningCenterVideoTutorial = () => import('../../components/support/learning-center/videoTutorial.vue' /* webpackChunkName: "components/support-learning-center-video-tutorial" */).then(c => wrapFunctional(c.default || c))
export const SupportNoticeAsideMenu = () => import('../../components/support/notice/AsideMenu.vue' /* webpackChunkName: "components/support-notice-aside-menu" */).then(c => wrapFunctional(c.default || c))
export const SupportNoticeContents = () => import('../../components/support/notice/NoticeContents.vue' /* webpackChunkName: "components/support-notice-contents" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
